### PR TITLE
Add settings.gradle to force sparkle.jar filename

### PR DESCRIPTION
**Pull request by alanz**
This ensures that the jar file is correct when building from a git location via stack.

### CODE REVIEW

**Comment by alanz** [comment]
The example using this is at https://github.com/alanz/sparkle-play

**Comment by mboes** [comment]
Thanks!

**Comment by mboes** [comment]
Is this a Gradle best practice to put this kind of metadata in the settings.gradle file? I assumed that file was only relevant for multi-project builds (multiple *gradle* projects that is).

**Comment by alanz** [comment]
I'm not sure about gradle best practice, but the default is to use the enclosing directory name, and stack sets that to a guid when checking out a specific hash. So either keep the properties file, or have some kind of script to rename the jar once it is built, using the stack query functions.

**Pull request merged**
