### PR TITLE
Invoke hs_init from within static initializer

### PR DESCRIPTION
**Pull request by robinbb**
This change greatly reduces the work done in the Sparkle.apply() method, which is invoked frequently in Sparkle operation - every time a Haskell closure must be invoked. The change arranges for `hs_init` to be called from the static initializer of the Sparkle class. This means that the Haskell run time system will have been initialized before any invocations of Sparkle.apply().

### CODE REVIEW

**Comment by robinbb** [comment]
I have made the requested changes. I nominate @alpmestan to test the changes, and possibly to see if they provide a measurable performance improvement. One would expect the improvement to be greater on multiprocessors. Regardless of the improvement, this is a simplification, which, if correct, is good. Does this change any linking flags to do with pthreads, I wonder?

**Comment by mboes** [comment]
> Regardless of the improvement, this is a valuable simplification.

Yup, agreed.

> Does this change any linking flags to do with pthreads, I wonder?

As noted in #22, I suspect the pthreads linker flags thing is an upstream issue: https://github.com/rrnewton/thread-local-storage/pull/6

**Comment by alpmestan** [comment]
I will be testing this patch next week indeed, locally and on a cluster. Will use that occasion to quantify the difference in performance, if noticeable. I will report whatever I find out here.

**Comment by alpmestan** [comment]
Robin's patch needs a very small modification (otherwise the call to `hs_init` crashes), but with that modification the application runs without any problem, both on a single machine and on a cluster, using 1 or more cores in both cases. He will push it soon.

A little note about our conversation from earlier today: according to [this post](http://blog.cloudera.com/blog/2014/05/apache-spark-resource-management-and-yarn-app-models/), a Spark **executor** consists in **a single JVM instance** dedicated to running tasks for a single application (where a task is a unit of work to be performed on a partition). An executor can use one or more cores from the machine (worker) it runs on. This means there's a 1:1:1 mapping between executors, JVMs and GHC runtimes.

**Comment by mboes** [comment]
> An executor can use one or more cores from the machine (worker) it runs on. 

Yes. This is consistent with the finding that the current spin lock do cap the scaling of some sparkle apps on multicore systems.

**Comment by alpmestan** [comment]
So, I've been able to benchmark this patch (against "vanilla" sparkle as well as Java). Here's the script that I've used.

``` sh
export DATASET_SIZE=10000
export DATASET_PARTITIONS=8

SPARK_SUBMIT="../../spark-2.0.1-bin-hadoop2.7/bin/spark-submit"

rm -r bench-*.jar*

for n in 1 2 4 8; do
    # work around /tmp getting filled too easily
    rm -r /tmp/blockmgr* /tmp/app* /tmp/spark*
    for v in micro-java.jar micro-patched-sparkle.jar micro-nonpatched-sparkle.jar; do
	SPARK_CMD=""
	if [ $v = "micro-java.jar" ]; then
	    SPARK_CMD="$SPARK_SUBMIT --class Micro --master local[$n] $v"
	else
	    SPARK_CMD="$SPARK_SUBMIT --master local[$n] $v"
	fi
	for i in $(seq 10); do
	    echo "Running $v on $n cores, sample $i"
	    echo $SPARK_CMD
	    $SPARK_CMD 2>&1 | grep "Job.*finished" | sed -e 's/took /\n/g' | tail -1 | sed -e 's/,/./g' | sed -e 's/ /\n/g' | head -1 >> bench-$v-$n-cores
	done
    done
done
```

The Haskell variant of the application used for this benchmark:

``` haskell
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE StaticPointers #-}
{-# LANGUAGE OverloadedStrings #-}
module Main where

import qualified Control.Distributed.Spark as S
import Control.Monad
import Data.Int
import System.Environment

main :: IO ()
main = do
  (n, nbPartitions) <- parseArgs
  conf <- S.newSparkConf "sparkle micro benchmark"
  sc <- S.newSparkContext conf
  rdd0 <- S.parallelize sc (dataset n)
      >>= S.repartition nbPartitions
  rdd1 <- S.map (S.closure $ static succ) rdd0
  -- just so that we actually force the call to map
  res <- S.collect rdd1
  print (head res)

parseArgs :: IO (Int32, Int32)
parseArgs = (,) <$> fmap read (getEnv "DATASET_SIZE")
                <*> fmap read (getEnv "DATASET_PARTITIONS")

dataset :: Int32 -> [Int32]
dataset n = [0 .. n]
```

The Java variant:

``` java
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import org.apache.spark.api.java.*;
import org.apache.spark.SparkConf;
import org.apache.spark.api.java.function.Function;

public class Micro {
  public static void main(String[] args) {
      Map<String, String> env = System.getenv();
      Integer n = Integer.parseInt(env.get("DATASET_SIZE"));
      Integer nbPartitions = Integer.parseInt(env.get("DATASET_PARTITIONS"));

      SparkConf conf = new SparkConf().setAppName("Micro Benchmark");
      JavaSparkContext sc = new JavaSparkContext(conf);

      ArrayList<Integer> arr = new ArrayList();
      for(Integer i = 0; i < n; i++)
	  arr.add(i);

      JavaRDD<Integer> data = sc.parallelize(arr).repartition(nbPartitions);
      JavaRDD<Integer> newData = data.map(new Function<Integer, Integer>() {
	      public Integer call(Integer i) {
		  return i+1;
	      }
	  });
      List<Integer> res = newData.collect();
      System.out.println("Result: " + res.get(0));
  }
}
```

Little note: I'm not entirely sure it's entirely fair to compare the Java runtimes to the Haskell one, as filling up an `ArrayList` in Java and turning it into a dataset is most likely cheaper than creating the equivalent Haskell list, converting it into a Java array and then turning that into a dataset. Let's just consider the run times of the Java variant as some kind of reference.

Withour further ado, here are the results (10k integers, 8 partitions, averaging run times for 10 runs of the same variant):

- Java, 1 core: **0.7047435s**
- Sparkle, no patch, 1 core: **0.8199866000000002s**
- Sparkle, w/ this patch, 1 core: **0.8245595s**

- Java, 2 cores: **0.6856437999999999s*
- Sparkle, no patch, 2 cores: **0.7789819s**
- Sparkle, w/ this patch, 2 cores: **0.7855395000000001s**

- Java, 4 cores: **0.620081s**
- Sparkle, no patch, 4 cores: **0.8088211000000001s**
- Sparkle, w/ this patch, 4 cores: **0.8116629s**

- Java, 8 cores: **0.6751459s**
- Sparkle, no patch, 8 cores: **0.8473244999999998s**
- Sparkle, w/ this patch, 8 cores: **0.8400166s**

I'll post another comment sometimes between tonight and tomorrow showing the run times for larger datasets (100k, 1M).

**Comment by robinbb** [comment]
I have made a change to the PR to correct the C type error that I made. I hope that either @alpmestan or @mboes will check to make sure that it compiles and runs correctly.

Regarding the benchmarks, above: the larger number of elements in the next benchmarks will tell us more. But, yes, @alpmestan, the initialization time for the list/ListArray is being measured, and so obscures the real value that we are trying to measure (the per-datum overhead for a low-cost computation).

**Comment by alpmestan** [comment]
Tested your change, it compiles and runs without any problem.

More benchmark results:

100k elements:

- Java, 1 core: **1.0577897000000003s**
- Sparkle, no patch, 1 core: **1.6683400999999995s**
- Sparkle, w/ patch, 1 core: **1.6469144s**

- Java, 2 cores: **0.9521751s**
- Sparkle, no patch, 2 cores: **2.2406514s**
- Sparkle, w/ patch, 2 cores: **2.2238350000000002s**

- Java, 4 cores: **0.9461203999999999s**
- Sparkle, no patch, 4 cores: **2.5031074s**
- Sparkle, w/ patch, 4 cores: **2.5257186000000003s**

- Java, 8 cores: **1.0090332s**
- Sparkle, no patch, 8 cores: **2.6072375s**
- Sparkle, w/ patch, 8 cores: **2.6044668s**

1 million elements:

- Java, 1 core: **3.6208317s**
- Sparkle, no patch, 1 core: **9.8089553s**
- Sparkle, w/ patch, 1 core: **9.1707512s**

- Java, 2 cores: **2.8068258s**
- Sparkle, no patch, 2 cores: **17.6298483s**
- Sparkle, w/ patch, 2 cores: **17.147438400000002s**

- Java, 4 cores: **2.6602421s**
- Sparkle, no patch, 4 cores: **17.7093128s**
- Sparkle, w/ patch, 4 cores: **17.6569145s**

- Java, 8 cores: **2.5243671s**
- Sparkle, no patch, 8 cores: **18.897142100000003s**
- Sparkle, w/ patch, 8 cores: **18.7224489s**

Let me know if you want me to try different numbers of partitions as well.

**Comment by robinbb** [comment]
@alpmestan How many actual cores did the machine have that ran the above benchmarks?

**Comment by robinbb** [comment]
Some ways to interpret the benchmarks:

1. The effect of the patch is only visible with 1M elements, and minutely improves the run time.
2. The patch seems not to be incorrect. @mboes will you merge?
3. On 1 core, Haskell is about 3x slower than Java (9 microseconds vs 3 microseconds per element)
4. On 2 cores, Haskell is about 8x slower than Java (16 microseconds vs 2 microseconds per element).

The patch does alleviate whatever causes the lack of parallelism on Java.

**Comment by alpmestan** [comment]
@robinbb 8 cores on this machine.

**Comment by alpmestan** [comment]
I think this patch can be merged, given that it 1/ is correct (doesn't make applications crash locally or on a cluster) 2/ certainly doesn't make things worse and 2/ even makes them noticeably better for a large enough data set. @mboes ?

We can make use of this benchmark (and future ones? We now have a somewhat decent way to measure the performance of sparkle vs vanilla spark, or the performance of patches to sparkle for that matter) to draw some conclusions unrelated to this patch's goal and exercise sparkle in different circumstances to e.g make sure we make an optimal use of the cores available on the machines sparkle runs on, which in my opinion should be one of the priorities in the upcoming weeks.

**Comment by mboes** [comment]
The benchmarks tell and odd story. Why is even the pure Java version not scaling with the number of cores? @alpmestan when you say "8 cores", have you checked that these are 8 physical cores? Or are they hyperthreaded? Further, it's strange that sparkle becomes markedly *slower* on multi core than on single core. If this is an AWS instance, what instance type are you using?

How many times did you run each benchmark? What variance did you get? I suspect that even for 1M elements, the differences in the numbers are just measurement error (very high variance to be expected on a multi tenant AWS instance, besides).

For the purposes of measuring overhead, I'd make the benchmark even simpler: just use parallel streams from the Java 8 Streams API. Fewer moving parts so may help us isolate what's going on. More importantly, we can remove interference from allocation times that way. Which I suspect single handedly explain much of the weirdness we're seeing above.

All the above notwithstanding, the patch seems plenty correct to me, as confirmed by @alpmestan's testing, and doesn't make matters worse. So merging.

Thanks @robinbb!

**Comment by mboes** [comment]
Something like this gist: https://gist.github.com/mboes/24810d495490eefbfe4740c2187316ea

**Comment by alpmestan** [comment]
> Why is even the pure Java version not scaling with the number of cores?

Maybe because of the number of partitions that I gave? It should however parallelize things properly with just 8 partitions.

> @alpmestan when you say "8 cores", have you checked that these are 8 physical cores? Or are they hyperthreaded?

Oops, sorry, I shouldn't reply when it's so late. I have 4 **actual** cores, 8 threads. These numbers come from running the app on my laptop, not AWS.

> How many times did you run each benchmark? What variance did you get? I suspect that even for 1M elements, the differences in the numbers are just measurement error (very high variance to be expected on a multi tenant AWS instance, besides).

Each variant (i.e for a fixed version of the app -- java, sparkle patched, sparkle non patched --, fixed dataset size and number of partitions, fixed number of core) was run 10 times and the number that I give above is obtained by averaging the run time of those 10 runs. Didn't keep all the numbers around so I unfortunately can't give the variance. It wasn't that big from what I could tell though.

> For the purposes of measuring overhead, I'd make the benchmark even simpler: just use parallel streams from the Java 8 Streams API. Fewer moving parts so may help us isolate what's going on. More importantly, we can remove interference from allocation times that way. Which I suspect single handedly explain much of the weirdness we're seeing above.

I agree that it would be nice to have a benchmark that doesn't penalize haskell so much, even though the main goal was to measure the difference between vanilla sparkle and a variant built against this patch, not haskell vs java.

**Comment by mboes** [comment]
> Each variant (i.e for a fixed version of the app -- java, sparkle patched, sparkle non patched --, fixed dataset size and number of partitions, fixed number of core) was run 10 times and the number that I give above is obtained by averaging the run time of those 10 runs. Didn't keep all the numbers around so I unfortunately can't give the variance. It wasn't that big from what I could tell though.

Ok good stuff.

> > Why is even the pure Java version not scaling with the number of cores?
> Maybe because of the number of partitions that I gave? It should however parallelize things properly with just 8 partitions.

Right. Something fishy going on! :)

**Pull request merged**
