### PR TITLE
Provide Dockerfile for non-linux environments

### PR DESCRIPTION
**Pull request by abailly**
I wanted to play with sparkle under Mac OS X which is not currently supported, hence I wrote a small Dockerfile that can be used to build sparkle itself and applications. Hope other people might find this useful.

### CODE REVIEW

**Comment by alpmestan** [comment]
This looks very useful for people running OS X or Windows, indeed! Thanks for this PR. My docker-fu being quite weak, I leave it to @mboes to provide feedback on the Dockerfile and merge when he's happy.

**Comment by mboes** [comment]
Looks good. Spark isn't included, but this is good enough for inline-java users. A few improvements I can think of:

* Use a stack installed GHC. That way we don't need to keep the `Dockerfile` and `stack.yaml` in sync.
* Stack has a `--docker` flag. Though I don't know if e.g. `stack --docker build` works on OS X. It would be nice if the user could drive the build from the OS X CLI as per usual entirely and have the docker thing be pretty much transparent.

But we can deal with those in a followup PR's.

**Comment by abailly** [comment]
* `stack setup` makes much more sense, yes. That's usually what I do, don't know why I did not do that now, 
* I second the idea of making things pretty much transparent. I did not try `stack --docker` because I am not sure what's the underlying container is. Ideally, as a user, I would like to decouple building sparkle and building packages, so that I could use sparkle commands locally and use docker to cross-compile sparkle packages. Does this makes sense? 

FWIW I will work full time on a spark project in the next couple of months so I would be happy to use sparkle if possible and having a clean workflow with a "transparent" docker would help. However having to run all commands through the container does seem a bit wasteful and cumbersome. If you think that can be helpful to others, I could keep on pushing PRs along this line.

**Comment by mboes** [comment]
> FWIW I will work full time on a spark project in the next couple of months so I would be happy to use sparkle if possible and having a clean workflow with a "transparent" docker would help. However having to run all commands through the container does seem a bit wasteful and cumbersome. If you think that can be helpful to others, I could keep on pushing PRs along this line.

Sounds awesome. See #44 for a few small steps in the direction mentioned previously. Would be glad for you to keep contributing to the Dockerfile and to anything else that helps make sparkle useful for you.

**Comment by abailly** [comment]
Thanks for the encouraging words. I will try to contribute as much as possible.

**Comment by mboes** [comment]
Using two separate containers, one for building sparkle and one for building packages makes sense to me. This should be possible for "out-of-tree" projects, where users have their own `stack.yaml`. It should just be a case of documenting that workflow I guess.

The user can provide a docker image explicitly on the command line, but the best bet is to have that in the config somewhere, with `docker: enable: true`. That way building is just `stack build`. It adds a bit of latency to every command to launch a new container each time, but it's a very common workflow in Stack, and one that has first class support.

**Pull request merged**
