### PR TITLE
Dockerfile tweaks

### PR DESCRIPTION
**Pull request by mboes**
* Don't install GHC - let `stack setup` do that (it'll pick a version
  that matches the `stack.yaml`).
* Install Gradle from PPA.
* Remove a few redundant packages.

It's now possible to `stack --docker build`. Updated README instructions
accordingly.

### CODE REVIEW

**Comment by mboes** [comment]
@abailly could you test this out? In particular, it would be great if you could confirm that the `stack --docker --docker-image sparkle build` command works for you on a non-Linux OS.

**Comment by abailly** [comment]
I can't right now: I am using docker for Mac 1.12rc and stack chokes on the version number :( Will try upgrading stack tomorrow

**Comment by mboes** [comment]
Hah! Sounds like an upstream issue. We ran into a similar one back in the summer of 2015: https://github.com/commercialhaskell/stack/issues/786. I assume your Stack version is more recent than than that.

**Comment by abailly** [comment]
After `stack upgrade` it works like a charm.

**Pull request merged**
