### PR TITLE
Switch to CircleCI 2.0

### PR DESCRIPTION
**Pull request by mboes**
Move from CircleCI 1.0 to CircleCI 2.0. A nice property about this
setup is that we use CircleCI workflows to setup the following
pipeline:

1. check out code.
2. if the `Dockerfile` or dependencies have changed, build a new image and publish to DockerHub.
3. Build the project inside a container spawned from the new image we just pushed.
4. Test

In this way, devs no longer have to check manually that
`tweag/sparkle` doesn't fall out-of-date compared to the `*.nix` files
etc for specifying system dependencies.

### CODE REVIEW

**Comment by mboes** [comment]
@dleprovost PTAL

**Comment by dleprovost** [comment]
Now if not in `master`, this is `lastest` which is runned, not `$tag`.
One solution will be to do the compilation in the first job only if not in `master` (with `docker run`), and add a circleCI filter only branch `master` for the second job. In this hypothesis, most of compilation commands can be factorized with yaml anchor I think.

**Comment by mboes** [comment]
Right. On further thought, I think the Docker image based approach for this is doomed. I'll think up an alternative.

**Comment by mboes** [comment]
Rebased on top of current master. What this means is that this PR cannot go green until we start using Stack 1.6.1, due to https://github.com/commercialhaskell/stack/issues/3624. We'll have to wait until Stack 1.6.1 hits Nixpkgs.

**Pull request merged**
