### PR TITLE
Pass args to main()

### PR DESCRIPTION
**Pull request by robinbb**

### CODE REVIEW

**Comment by robinbb** [comment]
@mboes The CircleCI tests have passed, but Wercker failed. I am unable to see the Wercker pipeline. I have made an account at Wercker, but not sure if that is necessary. I propose that the Wercker pipeline be public, if that is possible.

**Comment by mboes** [comment]
It's supposed be. Checking the settings.

**Comment by mboes** [comment]
Fixed the permissions. Good to know: in Wercker there are two levels of permissions, one for the project and one for each pipeline.

**Comment by mboes** [comment]
Looks like you forgot the checkin the argv folder.

Was curious to find out why CircleCI succeeds when Wercker fails. @robinbb looks like you unearthed a bug in Stack. `stack --docker` seems to ignore the exit code of the in-docker `stack` process. The Wecker build doesn't use `--docker` (since the build starts in the docker container already).

**Comment by robinbb** [comment]
@mboes Oops! Yes, I definitely did not construct the PR correctly the first time. Was too hasty. Fixed, now, I think. Regarding the dead code (around where GHC RTS options are set), that is there to show a developer how to configure the GHC RTS options on a worker node. That is the only way to set them, currently. I plan on submitting another PR in which the GHC RTS options are set via a Java system property.

**Comment by mboes** [comment]
OK would be grateful if you could preserve whitespace in existing files as per [style guide](https://github.com/tweag/guides/blob/master/style/Haskell.md) linked to from the https://github.com/tweag/sparkle/blob/master/CONTRIBUTING.md file. And then merge at your convenience.

Thanks for the PR!

**Comment by robinbb** [comment]
@mboes Yes, whitespace changes were made before style guide. Can you clarify spacing guidelines for non-Haskell (C/Java) code - 2 spaces, or 4 for indentation? Previously, there was tabs+spaces on same line, FYI, so there was not uniformly good guidance from existing code on correct spacing. I'll change the PR to have the correct spacing, if you let me know.

**Comment by mboes** [comment]
> Previously, there was tabs+spaces on same line,

I use the Emacs defaults for C indentation, set to "linux" style. That's the style of the bootstrap.c file you're editing. I ought to make that more explicit somewhere. For reference, those are 8 space tabs for indentation, spaces for alignment. Java uses 4 spaces, also an Emacs default.

**Comment by facundominguez** [comment]
Rebased master.

**Pull request merged**
