### PR TITLE
add missing bindings to callXXX methods

### PR DESCRIPTION
**Pull request by alpmestan**
Addresses #32.

### CODE REVIEW

**Comment by alpmestan** [comment]
Will add some tests early next week, to make sure this code actually works.

**Comment by alpmestan** [comment]
In the process of adding tests for those bindings, I get bitten by the fact that `withJVM` can only be called once and that hspec's way of running tests gets in the way of simply doing `withJVM [] $ hspec spec`.

**Comment by mboes** [comment]
What's wrong with `withJVM [] $ hspec spec`?

**Comment by alpmestan** [comment]
With the following:

``` haskell
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE OverloadedStrings #-}
module Language.JavaSpec where

import Data.ByteString (ByteString)
import Data.Int
import Data.Text (Text)
import GHC.TypeLits
import Language.Java
import Test.Hspec

main :: IO ()
main = withJVM [] (hspec spec)

spec :: Spec
spec = describe "callStatic" $ do
  it "allows to call double-returning static functions" $ do
    jstr <- reflect ("1.2345" :: Text)
    callStatic (sing :: Sing "java.lang.Double")
               "parseDouble"
               [coerce jstr]
      `shouldReturn` (1.2345 :: Double)

  it "allows to call int-returning static functions" $ do
    jstr <- reflect ("12345" :: Text)
    callStatic (sing :: Sing "java.lang.Integer")
               "parseInt"
               [coerce jstr]
      `shouldReturn` (12345 :: Int32)
```

I get:

```
[...]
inline-java-0.1: test (suite: spec)
             
Progress: 1/2
Language.Java
  callStatic
No JVM has been initialized yet.
             
Completed 2 action(s).
Test suite failure for package inline-java-0.1
    spec:  exited with: ExitFailure 14
Logs printed to console
```

If I push the `withJVM` call down into one of the `it` blocks, it works for that block but since `withJVM` can only be called once,  that approach won't get us far.

Want me to push what I have so that you can take a closer look?

**Comment by mboes** [comment]
> Want me to push what I have so that you can take a closer look?

Please do! :) Never harms to do so.

**Comment by alpmestan** [comment]
There you go.

**Comment by mboes** [comment]
:+1:

**Pull request merged**
